version: "3"
services:
  php:
    user: apache
    build:
      context: ./docker/php
    depends_on:
      - database
      - mail
    ports:
      - ${PORT_WEB_APP:-8000}:8000
      - ${PORT_BROWSERSYNC:-3000}:${PORT_BROWSERSYNC:-3000}
    volumes:
      - php:/var/www
      - ./docker/php/php.ini:/etc/php.ini
      - ./docker/php/httpd.conf:/etc/httpd/conf/httpd.conf
    working_dir: /var/www
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=_DUMMYDUMMYDUMMYDUMMYDUMMYDUMMY_
      - APP_ENV=local
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - PGHOST=database
      - PGUSER=postgres
      - CACHE_DRIVER=apc
      - SESSION_DRIVER=apc
      - TZ=Asia/Tokyo
      - MAIL_HOST=mail
      - MAIL_PORT=1025
      - MAIL_ENCRYPTION=null
      - LANG=C.UTF-8
      - LANGUAGE=en_US

  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - ${PORT_PGSQL:-0}:5432
    environment:
      - TZ=Asia/Tokyo
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS="--locale=ja_JP.utf8"

  mail:
    image: mailhog/mailhog
    ports:
      - ${PORT_WEB_MAIL:-8025}:8025

  phppgadmin:
    image: bitnami/phppgadmin
    ports:
      - ${PORT_WEB_PHPPGADMIN:-8432}:8080
    environment:
      DATABASE_HOST: database
    depends_on:
      - database

volumes:
  database:
  php:
